### ISSUE TITLE
Apple2ix fails to recognize some (apparantly) valid images

### ISSUE THREAD

**Issue by keenerb** [mauiaaron/apple2#25]
ftp://ftp.apple.asimov.net/pub/apple_II/images/games/rpg/legacy_of_ancients/

These disks report as "unreadable" to apple2ix, even though they work fine in Candyapple and KEGS on Android, and Applewin for Windows.

**Comment by mauiaaron** [comment]
Ah yes, I'm being too strict about file sizes here.  This will be fixed in an upcoming version.

For now, you should be able to work around this issue by truncating the last 3 bytes of each of these disk images, such that the file size for each becomes exactly 143360 bytes.

A command to do this on Unixy systems is `dd if=legacy_of_ancients_1.dsk of=loa1.dsk bs=1 count=143360`

**Comment by keenerb** [comment]
Fantastic.  Thanks for the quick reply!  I'm absolutely loving your custom keyboard implementation, "bad" keyboards are the bane of system emulators on Android.

**Comment by mauiaaron** [comment]
Glad you like the Apple2ix custom soft touch keyboard!  Yeah, there was no way I was going to play old school RPGs on my phone using the regular Android keyboard, lol!  Cheers,

**Comment by keenerb** [comment]
Your advice resolved the issue.

**Comment by mauiaaron** [comment]
Fix landed in `android_develop` branch and slated for 1.2.0 release.
